apiVersion: v1
kind: Service
metadata:
    name: dkron-web
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        app: dkron
        component: server
    clusterIP: None
    ports:
        -   protocol: TCP
            name: http
            port: 8080
